---
title: "WFH v Docked Comparisons"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      error = FALSE)

options(scipen=999)

```

```{r load_dependencies, include = FALSE}

## Load libraries/functions
library(knitr)
library(kableExtra)
library(ggplot2)
library(cowplot)


## Load visualization functions
lpath = "C:/Users/zachm/Documents/George Mason/Projects/Labor Flows Paper/R visualizations"
source(paste(lpath, "fxns_firm.R", sep = "/"))
source(paste(lpath, "fxns_general.R", sep = "/"))
source(paste(lpath, "fxns_labor.R", sep = "/"))
source(paste(lpath, "fxns_network_smry.R", sep = "/"))

```

```{r local_functions, include = FALSE}

## 3.1 tables
## Puts all the metrics into a single long table
#
kableize_3.1_all = function(df # List of data.frames for a scenario (e.g. wfh_docked_impact_tables)
                            ){
  
  
  scenarios = names(df)[grepl("3_1_", names(df))]
  wfh_list = df[scenarios]                        # Just grab the lists of interest...
  metrics = unique(wfh_list[[1]][[1]]$Metric)
  
  
  ## Move the locations side-by-side for ease of comparison
  tbls = list()
  for (scenario in scenarios){
    
    tmp_all = NULL
    for (metric in metrics){
      
      idA = grepl("Location A", names(wfh_list[[scenario]]))
      idB = grepl("Location B", names(wfh_list[[scenario]]))
      
      tmpA = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idA], function(x) x[x$Metric == metric, ])))
      tmpB = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idB], function(x) x[x$Metric == metric, ])))
      
      tmp_all = rbind(tmp_all, cbind(tmpA, tmpB[, 2:ncol(tmpB)]))
    }
    
    
    rownames(tmp_all) = NULL
    
    tbls[[scenario]] = tmp_all
  }
  
  
  ## Make it pretty
  tmp_scenario = list()
  for (metric in tbls[[1]]$Metric){
    
    tmp = do.call('rbind', lapply(tbls, function(x) x[x$Metric == metric, ])) # binds each metric together by row
    rownames(tmp) = gsub("3_1_[0-9]_", "", rownames(tmp))                     # Removes extraneous information from rownames
    tmp = tmp[, !(colnames(tmp) %in% "Metric")]                               # Removes the "Metric" column that gets added in the do.call step
    tmp = round(tmp, 2)                                                       # Standardize rounding
    
    tmp_scenario[[metric]] = tmp                                              # Set as list element for each scenario
  }
  
  
  ## All as 1 table...
  df_all = as.matrix(do.call('rbind', tmp_scenario))
  rownames(df_all) = gsub(".*\\.", "", rownames(df_all)) # Removes extraneous information that gets added to rownames when doing rbind
  colnames(df_all) = gsub("\\..*", "", colnames(df_all)) # Removes .1, .2, etc when combining headers (i.e docked for location A and B)
  
  
  ## Create Base Cable
  kbl_all = kable(df_all, digits = 2, align = 'c') %>%
    kable_styling(bootstrap_options = c("striped"), full_width = FALSE) %>%
    add_header_above(c(" " = 1, "Location A" = 3, "Location B" = 3)) 
  
  
  ## Add the row groupings 
  cnt = 1
  for (metric in metrics){
    
    if (!(metric %in% metrics[length(metrics)])){
      kbl_all = kbl_all %>% pack_rows(group_label = metric, start_row = cnt, end_row = cnt + 6)
    } else {kbl_all = kbl_all %>% pack_rows(group_label = metric, start_row = cnt, end_row = cnt + 5)}
    
    cnt = cnt + 6
  }
  
  
  return(kbl_all)
}


## 3.1 - individual metrics
kableize_3.1_ind = function(df # List of data.frames for a scenario (e.g. wfh_docked_impact_tables)
                            ){
  
  scenarios = names(df)[grepl("3_1_", names(df))]
  wfh_list = df[scenarios]                        # Just grab the lists of interest...
  metrics = unique(wfh_list[[1]][[1]]$Metric)
  
  
  ## Move the locations side-by-side for ease of comparison
  tbls = list()
  for (scenario in scenarios){
    
    tmp_all = NULL
    for (metric in metrics){
      
      idA = grepl("Location A", names(wfh_list[[scenario]]))
      idB = grepl("Location B", names(wfh_list[[scenario]]))
      
      tmpA = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idA], function(x) x[x$Metric == metric, ])))
      tmpB = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idB], function(x) x[x$Metric == metric, ])))
      
      tmp_all = rbind(tmp_all, cbind(tmpA, tmpB[, 2:ncol(tmpB)]))
    }
    
    
    rownames(tmp_all) = NULL
    
    tbls[[scenario]] = tmp_all
  }
  
  
  ## Make it pretty
  tmp_scenario = list()
  for (metric in tbls[[1]]$Metric){
    
    tmp = do.call('rbind', lapply(tbls, function(x) x[x$Metric == metric, ])) # binds each metric together by row
    rownames(tmp) = gsub("3_1_[0-9]_", "", rownames(tmp))                     # Removes extraneous information from rownames
    tmp = tmp[, !(colnames(tmp) %in% "Metric")]                               # Removes the "Metric" column that gets added in the do.call step
    tmp = round(tmp, 2)                                                       # Standardize rounding
    
    tmp_scenario[[metric]] = tmp                                              # Set as list element for each scenario
  }
  
  
  kbl_all = list()
  for (metric in names(tmp_scenario)){
    
    tmp = as.matrix(tmp_scenario[[metric]])
    rownames(tmp) = gsub(".*\\.", "", rownames(tmp))
    colnames(tmp) = gsub("\\..*", "", colnames(tmp))
    
    kbl_all[[metric]] = kable(tmp, digits = 2, align = 'c', 
                              caption = paste0("WFH vs Docked Comparison: ", metric)) %>%
      kable_styling(bootstrap_options = c("striped"), full_width = FALSE) %>%
      add_header_above(c(" " = 1, "Location A" = 3, "Location B" = 3)) 
  }
  
  
  return(kbl_all)
}



## 3.2 - Individual Metrics
## "wide"
kableize_3.2 = function(df
                        ){
  
  
  scenarios = names(df)[grepl("3_2_2", names(df))] # 3.2.2 and 3.2.3 appear to be identical...
  wfh_list = df[scenarios] # Just grab the lists of interest...
  metrics = unique(wfh_list[[1]][[1]]$Metric)
  
  out = list()
  ## This is if we want A next to B and then split skill/unskill 
  for (scenario in scenarios){
    
    tmp_s = NULL
    tmp_u = NULL
    for (metric in metrics){
      
      ## Locations
      idA = grepl("Location A", names(wfh_list[[scenario]]))
      idB = grepl("Location B", names(wfh_list[[scenario]]))
      
      ## Skills
      ids = grepl("_skilled", names(wfh_list[[scenario]]))
      idu = grepl("_unskilled", names(wfh_list[[scenario]]))
      
      
      ## Skilled Workers
      tmpAs = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idA & ids], function(x) x[x$Metric == metric, ])))
      tmpBs = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idB & ids], function(x) x[x$Metric == metric, ])))
      
      ## Unskilled Workers
      tmpAu = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idA & idu], function(x) x[x$Metric == metric, ])))
      tmpBu = cbind(do.call('rbind', lapply(wfh_list[[scenario]][idB & idu], function(x) x[x$Metric == metric, ])))
      
      
      tmp_s = rbind(tmp_s, cbind(tmpAs, tmpBs[, 2:ncol(tmpBs)]))
      tmp_u = rbind(tmp_u, cbind(tmpAu, tmpBu[, 2:ncol(tmpBu)]))
    }
    
    
    rownames(tmp_s) = NULL
    rownames(tmp_u) = NULL
    
    
    out[[scenario]]$Skilled = tmp_s
    out[[scenario]]$unSkilled = tmp_u
  }
  
  
  
  tmp_scenario = list()
  for (metric in out[[1]][[1]]$Metric){
    
    
    tmpS = do.call('rbind', lapply(out, function(x) x$Skilled[x$Skilled$Metric == metric, ]))
    rownames(tmpS) = gsub("3_2_[0-9]_", "", rownames(tmpS))
    tmpS = tmpS[, !(colnames(tmpS) %in% "Metric")]
    
    tmpU = do.call('rbind', lapply(out, function(x) x$unSkilled[x$unSkilled$Metric == metric, ]))
    rownames(tmpU) = gsub("3_2_[0-9]_", "", rownames(tmpU))
    tmpU = tmpU[, !(colnames(tmpU) %in% "Metric")]
    
    tmp = cbind(tmpS[, 1:3], tmpU[,1:3], tmpS[, 4:6], tmpU[, 4:6])
    
    tmp = round(tmp, 2)
    
    tmp_scenario[[metric]] = tmp
  }
  
  
  
  ## Pretty Individual tables
  all_kbls = list()
  for (nm in names(tmp_scenario)){
    
    tmp = tmp_scenario[[nm]]
    colnames(tmp) = gsub("\\..*", "", colnames(tmp))
    kmp = kable(tmp, digits = 2, align = 'c', 
                caption = paste0("WFH vs Docked Comaprison: ", nm)) %>%
      kable_styling(bootstrap_options = c("striped"), full_width = FALSE) %>%
      add_header_above(c(" " = 1, "Skilled" = 3, "unSkilled" = 3, "Skilled" = 3, "unSkilled" = 3)) %>% 
      add_header_above(c(" " = 1, "Location A" = 6, "Location B" = 6)) 
    
    all_kbls[[nm]] = kmp
  }
  
  
  return(all_kbls)
}



```

#### Last run: `r format(Sys.time(), "%b %d, %Y")` 

## Section 3.1 Results {.tabset}

<!---
### All Metrics 
--->
```{r make_pretty_3_1_tables, eval = FALSE}

kableize_3.1_all(wfh_docked_impact_tables)

```


```{r create_3_1_tables_ind, include = FALSE}

kbls = kableize_3.1_ind(wfh_docked_impact_tables)

```

```{r print_3_1_tables_ind, results = 'asis', include = TRUE}

for (nm in names(kbls)){
  
  cat(paste0("### ", nm))
  cat("\n")
  
  cat(kbls[[nm]])
  
}

```


## Section 3.2 Results {.tabset}

```{r create_3_2_2_tables_wide, include = FALSE}

kbls = kableize_3.2(wfh_docked_impact_tables)

```

```{r print_3_2_2_tables_wide, include = TRUE, results = 'asis'}

for (nm in names(kbls)){
  
  cat(paste0("### ", nm))
  cat("\n")
  
  cat(kbls[[nm]])
  
}


```

